source 'https://github.com/CocoaPods/Specs'

project 'AFNetworking Tests'
workspace '../AFNetworking'
inhibit_all_warnings!

def import_pods
  pod 'OCMock', '~> 2.1.1'
  pod 'Expecta', '~> 0.2.1'
  pod 'AFNetworking', :path => '../'
end

target 'iOS Tests' do
  platform :ios, '7.0'
  import_pods
end

target 'OS X Tests' do
  platform :osx, '10.9'
  import_pods
end
