source 'https://github.com/CocoaPods/Specs'

xcodeproj 'AFNetworking Tests'
workspace '../AFNetworking'
inhibit_all_warnings!

def import_afn
  pod 'AFNetworking', :path => '../'
end

def import_test_libs
  pod 'OCMock', '~> 2.1.1'
  pod 'Expecta', '~> 0.2.1'
end

target 'iOS Test Application' do
  platform :ios, '6.0'
  import_afn
end

target :ios do
  platform :ios, '6.0'
  link_with 'iOS Tests', 'iOS Application Tests'
  import_afn
  import_test_libs
end

target :osx do
  platform :osx, '10.9'
  link_with 'OS X Tests'
  import_afn
  import_test_libs
end
